name: Detectar categorias de anotações em classes Java modificadas

on:
  pull_request:

jobs:
  verificar-categorias-anotacoes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detectar arquivos modificados com @CrivoObserver
        id: anotacoes
        run: |
          git fetch origin ${{ github.base_ref }}
          arquivos=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep '\.java$' || true)

          mensagem=""
          for arquivo in $arquivos; do
            if grep -q '@CrivoObserver' "$arquivo"; then
              echo "::warning file=$arquivo::[⚠️ Crítico] Esta classe contém @CrivoObserver. Verifique se há impacto no fluxo de redisparo de politica de crédito!"
              mensagem+="🚨 Arquivo \`$arquivo\` contém @CrivoObserver\n"
            fi
          done

          echo "mensagem<<EOF" >> $GITHUB_OUTPUT
          echo -e "$mensagem" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comentar no PR se houver anotação crítica
        if: steps.anotacoes.outputs.mensagem != ''
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### ⚠️ Anotações críticas detectadas:\n${{ steps.anotacoes.outputs.mensagem }}`
            })
