name: Detectar categorias de anotações em classes Java modificadas

on:
  pull_request:

jobs:
  verificar-categorias-anotacoes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verificar anotações por categoria
        run: |
          git fetch origin ${{ github.base_ref }}
          arquivos=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep '\.java$' || true)

          for arquivo in $arquivos; do
            if grep -q '@CrivoObserver' "$arquivo"; then
              echo "::warning file=$arquivo::[⚠️ Crítico] Esta classe contém @CrivoObserver. Verifique se há impacto no fluxo de redisparo de politica de credito!"
            fi
          done
